###
### Get All Reservations
###

GET http://localhost:3000/reservations/getReservations


###
### Get Reservation by Id
###

GET http://localhost:3000/reservations/getReservations/64d93b8de9f88cab732bf1bf


###
### Update a Reservation (Partial Update)
###

PATCH http://localhost:3000/reservations/getReservations/64d93b8de9f88cab732bf1bf
Content-Type: application/json

{
  "eventName": "Updated Event"
}


###
### Create a New Reservation
###
POST http://localhost:3000/reservations/create
Content-Type: application/json

{
  "eventName": "Breakfast",
  "eventDate": "2023-09-15T08:00:00Z",
  "userName": "Berat Yilmaz",
  "location": "indoor",
  "numberOfPeople": 4
}


###
### Delete by Id
###

DELETE http://localhost:3000/reservations/getReservations/64da266fd2110ddfd4c818f7

