### User Creation Request
POST http://localhost:3000/user/signup
Content-Type: application/json

{
  "name": "Berat Yilmaz",
  "email": "hallo3@gmail.com",
  "password": "passtestpass",
  "passwordConfirm": "passtestpass"
}

### Login with true data
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "beratyilmaz.job@gmail.com",
  "password": "passtestpass"
}

### Login 
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "beratyilmaz.job@gmail.com"
}

### Get All Users
GET http://localhost:3000/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTdhZDEzMjAzNjg1NGY0YTE2NTJhOCIsImlhdCI6MTY5MjkwNDcyNCwiZXhwIjoxNjkzNTA5NTI0fQ.uUz6ZYQ-__ioSZspUPDGChkZyT2EKLBt5mvPl6Pggx4


### Delete user with unauthorized account =  role:user
DELETE http://localhost:3000/user/64e51cee65b8e507ca192ab5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTdhZDEzMjAzNjg1NGY0YTE2NTJhOCIsImlhdCI6MTY5MjkwNDcyNCwiZXhwIjoxNjkzNTA5NTI0fQ.uUz6ZYQ-__ioSZspUPDGChkZyT2EKLBt5mvPl6Pggx4

### Delete user with authorized account = role:admin
DELETE http://localhost:3000/user/64e51cee65b8e507ca192ab5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTdiNjFjYmY0NGFlMjc1YTM3MDIwNCIsImlhdCI6MTY5MjkwNzAzNywiZXhwIjoxNjkzNTExODM3fQ.qY_MZZVlpsB0oect5VrZoWNxqVSgyuGCOWFwQAHohy4

### Forgot Password
POST http://localhost:3000/user/forgotPassword
Content-Type: application/json

{
  "email": "beratyilmaz.job@gmail.com"
}