### User Creation Request
POST http://localhost:3000/user/signup
Content-Type: application/json

{
  "name": "Berat Yilmaz",
  "email": "beratyilmaz.1@gmail.com",
  "password": "passtestpass",
  "passwordConfirm": "passtestpass"
}

### Login with true data
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "beratyilmaz.job@gmail.com",
  "password": "passtestpass"
}

### Login 
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "beratyilmaz.job@gmail.com"
}

### Get All Users
GET http://localhost:3000/user/
Authorization: Bearer <token_here>

